version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.11
  build:
    commands:
      - |
        cat << BUILD > deploy_to_cloudfront.py
        ${indent(8, script)}
        BUILD
      - python deploy_to_cloudfront.py
